Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Collecting coverage==4.0a6
  Could not find a version that satisfies the requirement coverage==4.0a6 (from versions: 3.0b3, 3.0, 3.0.1, 3.1b1, 3.1, 3.2b1, 3.2b2, 3.2b3, 3.2b4, 3.2, 3.3, 3.3.1, 3.4b1, 3.4b2, 3.4, 3.5b1, 3.5, 3.5.1b1, 3.5.1, 3.5.2b1, 3.5.2, 3.5.3, 3.6b1, 3.6b2, 3.6b3, 3.6, 3.7, 3.7.1, 4.0a1, 4.0a2, 4.0a3, 4.0a4, 4.0a5)
No matching distribution found for coverage==4.0a6
Package search: {'_pypi_ordering': False, 'version': '3.7.1', 'name': 'coverage', 'summary': 'Code coverage measurement for Python'}
Creating standard recipe for coverage-4.0a6
Using url https://pypi.python.org/packages/source/c/coverage/coverage-4.0a6.tar.gz (288 KB) for coverage.
Downloading coverage
Unpacking coverage...
done
working in /tmp/tmp1alVwCconda_skeleton_coverage-4.0a6.tar.gz
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.0. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    from setuptools import setup
ImportError: No module named setuptools

Applying patch: '/tmp/tmp1alVwCconda_skeleton_coverage-4.0a6.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmp1alVwCconda_skeleton_coverage-4.0a6.tar.gz/coverage-4.0a6
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install coverage==4.0a6
Error: Could not pip install coverage==4.0a6
