Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Collecting honcho==0.6.6
  Downloading http://localhost/packages/2.7/h/honcho/honcho-0.6.6-py2.py3-none-any.whl
Installing collected packages: honcho
Successfully installed honcho-0.6.6
Traceback (most recent call last):
  File "__tmpfile__.py", line 1, in <module>
    import pkg_resources;
ImportError: No module named pkg_resources
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Package search: {'_pypi_ordering': False, 'version': '0.6.6', 'name': 'honcho', 'summary': 'Honcho: a python clone of Foreman. For managing Procfile-based applications.'}
Creating standard recipe for honcho-0.6.6
Error: Could not parse url for honcho: UNKNOWN

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install honcho==0.6.6
Getting dependencies...
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-pipbuild", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 80, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 349, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 360, in execute
    build_package(package, version, noarch_python=args.noarch_python)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 304, in build_package
    noarch_python=noarch_python)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 240, in make_recipe
    depends = get_all_dependencies(package, version)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 219, in get_all_dependencies
    output = subprocess.check_output(cmd3args)
  File "/home/ubuntu/miniconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/ubuntu/miniconda/envs/_pipbuild_/bin/python', '__tmpfile__.py']' returned non-zero exit status 1
