Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/commands/install.py", line 268, in run
    wheel_cache
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 268, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 207, in from_line
    wheel_cache=wheel_cache)
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 66, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2960, in parse
    reqs = list(parse_requirements(s))
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2904, in parse_requirements
    "version spec")
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2869, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'beautifulsoup==>=3.2.1,<3.3.0', 'at', '==>=3.2.1,<3.3.0')

Package search: {'_pypi_ordering': False, 'version': '7.6.0', 'name': 'sentry', 'summary': 'A realtime logging and aggregation server.'}
Creating standard recipe for sentry-7.6.0
Converting recipe in /home/ubuntu/pypi-conda-builds/sentry
package = sentry
   dependencies = [u'beautifulsoup >=3.2.1,<3.3.0', u'celery >=3.1.8,<3.2.0', u'cssutils >=0.9.9,<0.10.0', u'django >=1.6.0,<1.7', u'django-bitfield >=1.7.0,<1.8.0', u'django-crispy-forms >=1.4.0,<1.5.0', u'django-paging >=0.2.5,<0.3.0', u'django-jsonfield >=0.9.13,<0.10.0', u'django-picklefield >=0.3.0,<0.4.0', u'django-recaptcha >=1.0.0,<1.1.0', u'django-social-auth >=0.7.28,<0.8.0', u'django-statsd-mozilla >=0.3.14.0,<0.3.15.0', u'django-sudo >=1.1.3,<1.2.0', u'django-templatetag-sugar >=0.1.0', u'djangorestframework >=2.3.8,<2.4.0', u'email-reply-parser >=0.2.0,<0.3.0', u'enum34 >=0.9.18,<0.10.0', u'exam >=0.5.1', u'gunicorn >=19.2.1,<20.0.0', u'ipaddr >=2.1.11,<2.2.0', u'logan >=0.7.1,<0.8.0', u'lxml >=3.4.1', u'mock >=0.8.0', u'nydus >=0.11.0,<0.12.0', u'markdown >=2.4.1,<2.5.0', u'petname >=1.7,<1.8', u'progressbar >=2.2,<2.4', u'pytest', u'pytest-django', u'python-dateutil >=2.0.0,<3.0.0', u'python-memcached >=1.53,<2.0.0', u'raven >=5.3.0', u'redis >=2.7.0,<2.11.0', u'requests[security] >=2.5.1,<2.6.0', u'simplejson >=3.1.0,<3.4.0', u'six >=1.6.0,<2.0.0', u'setproctitle >=1.1.7,<1.2.0', u'statsd >=3.1.0,<3.2.0', u'south ==1.0.1', u'toronado >=0.0.4,<0.1.0', u'ua-parser >=0.3.5', u'urllib3 >=1.7.1,<1.8.0']
Creating standard recipe for beautifulsoup->=3.2.1,<3.3.0
Error: Version >=3.2.1,<3.3.0 of beautifulsoup is not available on PyPI.

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install beautifulsoup==>=3.2.1,<3.3.0
Error: Could not pip install beautifulsoup==>=3.2.1,<3.3.0
