Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Collecting vobject==0.8.1c
  Downloading http://localhost/packages/source/v/vobject/vobject-0.8.1c.tar.gz (59kB)
setuptools must be installed to install from a source distribution
Package search: {'_pypi_ordering': False, 'version': '0.8.1c', 'name': 'vobject', 'summary': 'VObject: module for reading vCard and vCalendar files'}
Creating standard recipe for vobject-0.8.1c
Using url https://pypi.python.org/packages/source/v/vobject/vobject-0.8.1c.tar.gz (59 KB) for vobject.
Downloading vobject
Using cached download
Unpacking vobject...
done
working in /tmp/tmpu8EGDaconda_skeleton_vobject-0.8.1c.tar.gz
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.0. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

---------------------------------------------------------------------------
This script requires setuptools version 0.6c9 to run (even to display
help).  I will attempt to download it for you (from
http://pypi.python.org/packages/2.7/s/setuptools/), but
you may need to enable firewall access for this script first.
I will start the download in 15 seconds.

(Note: if this machine does not have network access, please obtain the file

   http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c9-py2.7.egg

and place it in this directory before rerunning this script.)
---------------------------------------------------------------------------
Downloading http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c9-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    use_setuptools()
  File "/tmp/tmpu8EGDaconda_skeleton_vobject-0.8.1c.tar.gz/vobject-0.8.1c/ez_setup/__init__.py", line 95, in use_setuptools
    return do_download()       
  File "/tmp/tmpu8EGDaconda_skeleton_vobject-0.8.1c.tar.gz/vobject-0.8.1c/ez_setup/__init__.py", line 89, in do_download
    egg = download_setuptools(version, download_base, to_dir, download_delay)
  File "/tmp/tmpu8EGDaconda_skeleton_vobject-0.8.1c.tar.gz/vobject-0.8.1c/ez_setup/__init__.py", line 150, in download_setuptools
    src = urllib2.urlopen(url)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

Applying patch: '/tmp/tmpu8EGDaconda_skeleton_vobject-0.8.1c.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpu8EGDaconda_skeleton_vobject-0.8.1c.tar.gz/vobject-0.8.1c
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install vobject==0.8.1c
Error: Could not pip install vobject==0.8.1c
